#!/usr/bin/env python3
"""Generate LAMMPS input files using ASE.

Converts POSCAR/CIF structures to LAMMPS data format and generates
input scripts with appropriate pair styles.
"""

import argparse
import json
import sys
from pathlib import Path

_simflow_root = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(_simflow_root))

from runtime.simflow_core.script_contracts import add_helper_recording_args, maybe_record_helper_run

try:
    from ase.io import read, write
except ImportError:
    print(json.dumps({"status": "error", "message": "ASE not installed"}))
    sys.exit(1)


PAIR_STYLES = {
    "eam/alloy": {"suffix": ".eam", "description": "EAM alloy potential"},
    "eam": {"suffix": ".eam", "description": "EAM potential"},
    "lj/cut": {"suffix": "", "description": "Lennard-Jones"},
    "tersoff": {"suffix": ".tersoff", "description": "Tersoff potential"},
    "airebo": {"suffix": ".CH", "description": "AIREBO potential"},
    "sw": {"suffix": ".sw", "description": "Stillinger-Weber"},
}

SUPPORTED_JOB_TYPES = {"minimize", "nvt", "npt", "nve"}


def _force_field_provenance(pair_style: str, pair_coeff: str, params: dict) -> dict:
    """Record force-field source information without copying potential content."""
    potential_files = params.get("potential_files") or params.get("force_field_files") or []
    if isinstance(potential_files, str):
        potential_files = [potential_files]
    return {
        "pair_style": pair_style,
        "pair_coeff": pair_coeff,
        "potential_files": potential_files,
        "source": params.get("force_field_source", "user_provided_or_lammps_runtime"),
        "redistributed_by_simflow": False,
        "note": "SimFlow records force-field provenance only; it does not vendor or validate proprietary potential content.",
    }


def _build_warnings(pair_style: str, pair_coeff: str, params: dict) -> list[dict]:
    warnings = []
    if pair_style not in PAIR_STYLES:
        warnings.append({
            "code": "unknown_pair_style",
            "message": "Pair style is not in SimFlow's small helper list; review against LAMMPS documentation before running.",
        })
    if not pair_coeff.strip():
        warnings.append({
            "code": "missing_pair_coeff",
            "message": "pair_coeff is required for a meaningful LAMMPS input.",
        })
    if params.get("force_field_source") in (None, ""):
        warnings.append({
            "code": "force_field_source_not_documented",
            "message": "Record potential provenance before using this input for scientific claims.",
        })
    return warnings


def structure_to_lammps(input_file: str, output_data: str, atom_style: str = "atomic") -> dict:
    """Convert structure file to LAMMPS data format using ASE."""
    atoms = read(input_file)
    write(output_data, atoms, format="lammps-data")

    return {
        "input_file": input_file,
        "output_data": output_data,
        "num_atoms": len(atoms),
        "elements": list(set(atoms.get_chemical_symbols())),
        "cell": atoms.cell.tolist(),
    }


def generate_input_script(
    job_type: str,
    data_file: str,
    pair_style: str,
    pair_coeff: str,
    output_path: str,
    params: dict = None,
) -> str:
    """Generate LAMMPS input script."""
    params = params or {}
    atom_style = params.get("atom_style", "atomic")

    lines = [
        "# LAMMPS input script - generated by SimFlow",
        f"# Job type: {job_type}",
        "",
        "# Initialization",
        f"units           {params.get('units', 'metal')}",
        f"dimension       {params.get('dimension', 3)}",
        f"boundary        {params.get('boundary', 'p p p')}",
        f"atom_style      {atom_style}",
        "",
        "# Read data",
        f"read_data       {data_file}",
        "",
        "# Potential",
        f"pair_style      {pair_style}",
        f"pair_coeff      {pair_coeff}",
        "",
        "# Neighbor list",
        "neighbor        2.0 bin",
        "neigh_modify    every 1 delay 0 check yes",
        "",
        "# Thermodynamic output",
        "thermo_style    custom step temp pe ke etotal press vol",
        f"thermo          {params.get('thermo_interval', 100)}",
        "",
        f"timestep        {params.get('timestep', 0.001)}",
    ]

    if job_type == "minimize":
        lines.extend([
            "",
            "# Energy minimization",
            f"min_style       {params.get('min_style', 'cg')}",
            f"minimize        {params.get('etol', 1e-6)} {params.get('ftol', 1e-8)} "
            f"{params.get('maxiter', 10000)} {params.get('maxeval', 100000)}",
        ])
    elif job_type in ("nvt", "npt", "nve"):
        temp = params.get("temperature", 300)
        nsteps = params.get("nsteps", 10000)
        seed = params.get("seed", 12345)

        if job_type == "nvt":
            lines.extend([
                "",
                "# NVT ensemble",
                f"velocity        all create {temp} {seed}",
                f"fix             1 all nvt temp {temp} {temp} {params.get('tdamp', 0.1)}",
                f"run             {nsteps}",
                "unfix           1",
            ])
        elif job_type == "npt":
            pressure = params.get("pressure", 0)
            lines.extend([
                "",
                "# NPT ensemble",
                f"velocity        all create {temp} {seed}",
                f"fix             1 all npt temp {temp} {temp} {params.get('tdamp', 0.1)} "
                f"iso {pressure} {pressure} {params.get('pdamp', 1.0)}",
                f"run             {nsteps}",
                "unfix           1",
            ])
        else:  # nve
            lines.extend([
                "",
                "# NVE ensemble",
                "fix             1 all nve",
                f"run             {nsteps}",
                "unfix           1",
            ])

    dump_file = params.get("dump_file", "dump.lammps")
    dump_interval = params.get("dump_interval", 100)
    lines.extend([
        "",
        "# Dump trajectory",
        f"dump            1 all custom {dump_interval} {dump_file} id type x y z vx vy vz",
        "",
        "# Final output",
        f"write_data      {params.get('output_data', 'final.data')}",
        f"write_restart   {params.get('restart_file', 'restart.lammps')}",
    ])

    content = "\n".join(lines) + "\n"
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content)
    return str(out)


def generate_lammps_inputs(
    input_file: str,
    job_type: str,
    output_dir: str,
    *,
    pair_style: str = "lj/cut",
    pair_coeff: str = "* * 1.0 1.0",
    params: dict = None,
) -> dict:
    """Generate a small, traceable LAMMPS input package."""
    params = params or {}
    normalized_job = job_type.strip().lower().replace("-", "_")
    if normalized_job not in SUPPORTED_JOB_TYPES:
        return {
            "status": "needs_clarification",
            "message": f"Unsupported LAMMPS helper job type: {job_type}",
            "supported_job_types": sorted(SUPPORTED_JOB_TYPES),
        }

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    data_path = output_path / "data.lammps"
    input_path = output_path / "in.lammps"
    manifest_path = output_path / "lammps_input_manifest.json"

    structure_info = structure_to_lammps(input_file, str(data_path), atom_style=params.get("atom_style", "atomic"))
    generate_input_script(
        normalized_job,
        data_path.name,
        pair_style,
        pair_coeff,
        str(input_path),
        params,
    )
    warnings = _build_warnings(pair_style, pair_coeff, params)
    manifest = {
        "software": "lammps",
        "job_type": normalized_job,
        "units": params.get("units", "metal"),
        "atom_style": params.get("atom_style", "atomic"),
        "pair_style": pair_style,
        "pair_coeff": pair_coeff,
        "force_field_provenance": _force_field_provenance(pair_style, pair_coeff, params),
        "source_structure": input_file,
        "generated_files": [str(input_path), str(data_path)],
        "warnings": warnings,
        "status": "warning" if warnings else "success",
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    return {
        "status": "success",
        "job_type": normalized_job,
        "pair_style": pair_style,
        "files_generated": [str(input_path), str(data_path), str(manifest_path)],
        "structure": structure_info,
        "manifest": manifest,
        "warnings": warnings,
    }


def main():
    parser = argparse.ArgumentParser(description="Generate LAMMPS inputs using ASE")
    parser.add_argument("--input", required=True, help="Input structure (POSCAR/CIF)")
    parser.add_argument("--job-type", required=True,
                        choices=["minimize", "nvt", "npt", "nve"],
                        help="Simulation type")
    parser.add_argument("--pair-style", default="eam/alloy",
                        help=f"LAMMPS pair style. Options: {list(PAIR_STYLES.keys())}")
    parser.add_argument("--pair-coeff", required=True,
                        help="pair_coeff line (e.g., '* * Si.eam Si')")
    parser.add_argument("--output-dir", default="lammps_input", help="Output directory")
    parser.add_argument("--params", type=str, default="{}",
                        help="JSON string of additional parameters")
    add_helper_recording_args(parser, default_stage="computation")
    args = parser.parse_args()

    try:
        params = json.loads(args.params)
        output_dir = Path(args.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        result = generate_lammps_inputs(
            args.input,
            args.job_type,
            str(output_dir),
            pair_style=args.pair_style,
            pair_coeff=args.pair_coeff,
            params=params,
        )
        result = maybe_record_helper_run(
            args=args,
            result=result,
            script_path=Path(__file__).resolve(),
            helper_name="lammps_generate_inputs",
            software="lammps",
            input_paths=[args.input],
            output_paths=result["files_generated"],
        )
        print(json.dumps(result, indent=2))
    except Exception as e:
        print(json.dumps({"status": "error", "message": str(e)}))
        sys.exit(1)


if __name__ == "__main__":
    main()
