#!/usr/bin/env python3
"""Generate LAMMPS input files using ASE.

Converts POSCAR/CIF structures to LAMMPS data format and generates
input scripts with appropriate pair styles.
"""

import argparse
import json
import sys
from pathlib import Path

try:
    from ase.io import read, write
except ImportError:
    print(json.dumps({"status": "error", "message": "ASE not installed"}))
    sys.exit(1)


PAIR_STYLES = {
    "eam/alloy": {"suffix": ".eam", "description": "EAM alloy potential"},
    "eam": {"suffix": ".eam", "description": "EAM potential"},
    "lj/cut": {"suffix": "", "description": "Lennard-Jones"},
    "tersoff": {"suffix": ".tersoff", "description": "Tersoff potential"},
    "airebo": {"suffix": ".CH", "description": "AIREBO potential"},
    "sw": {"suffix": ".sw", "description": "Stillinger-Weber"},
}


def structure_to_lammps(input_file: str, output_data: str, atom_style: str = "atomic") -> dict:
    """Convert structure file to LAMMPS data format using ASE."""
    atoms = read(input_file)
    write(output_data, atoms, format="lammps-data")

    return {
        "input_file": input_file,
        "output_data": output_data,
        "num_atoms": len(atoms),
        "elements": list(set(atoms.get_chemical_symbols())),
        "cell": atoms.cell.tolist(),
    }


def generate_input_script(
    job_type: str,
    data_file: str,
    pair_style: str,
    pair_coeff: str,
    output_path: str,
    params: dict = None,
) -> str:
    """Generate LAMMPS input script."""
    params = params or {}

    lines = [
        "# LAMMPS input script - generated by SimFlow",
        f"# Job type: {job_type}",
        "",
        "# Initialization",
        f"units           {params.get('units', 'metal')}",
        f"dimension       {params.get('dimension', 3)}",
        f"boundary        {params.get('boundary', 'p p p')}",
        f"atom_style      {atom_style}",
        "",
        "# Read data",
        f"read_data       {data_file}",
        "",
        "# Potential",
        f"pair_style      {pair_style}",
        f"pair_coeff      {pair_coeff}",
        "",
        "# Neighbor list",
        "neighbor        2.0 bin",
        "neigh_modify    every 1 delay 0 check yes",
        "",
        "# Thermodynamic output",
        "thermo_style    custom step temp pe ke etotal press vol",
        f"thermo          {params.get('thermo_interval', 100)}",
        "",
        f"timestep        {params.get('timestep', 0.001)}",
    ]

    atom_style = params.get("atom_style", "atomic")

    if job_type == "minimize":
        lines.extend([
            "",
            "# Energy minimization",
            f"min_style       {params.get('min_style', 'cg')}",
            f"minimize        {params.get('etol', 1e-6)} {params.get('ftol', 1e-8)} "
            f"{params.get('maxiter', 10000)} {params.get('maxeval', 100000)}",
        ])
    elif job_type in ("nvt", "npt", "nve"):
        temp = params.get("temperature", 300)
        nsteps = params.get("nsteps", 10000)
        seed = params.get("seed", 12345)

        if job_type == "nvt":
            lines.extend([
                "",
                "# NVT ensemble",
                f"velocity        all create {temp} {seed}",
                f"fix             1 all nvt temp {temp} {temp} {params.get('tdamp', 0.1)}",
                f"run             {nsteps}",
                "unfix           1",
            ])
        elif job_type == "npt":
            pressure = params.get("pressure", 0)
            lines.extend([
                "",
                "# NPT ensemble",
                f"velocity        all create {temp} {seed}",
                f"fix             1 all npt temp {temp} {temp} {params.get('tdamp', 0.1)} "
                f"iso {pressure} {pressure} {params.get('pdamp', 1.0)}",
                f"run             {nsteps}",
                "unfix           1",
            ])
        else:  # nve
            lines.extend([
                "",
                "# NVE ensemble",
                "fix             1 all nve",
                f"run             {nsteps}",
                "unfix           1",
            ])

    dump_file = params.get("dump_file", "dump.lammps")
    dump_interval = params.get("dump_interval", 100)
    lines.extend([
        "",
        "# Dump trajectory",
        f"dump            1 all custom {dump_interval} {dump_file} id type x y z vx vy vz",
        "",
        "# Final output",
        f"write_data      {params.get('output_data', 'final.data')}",
        f"write_restart   {params.get('restart_file', 'restart.lammps')}",
    ])

    content = "\n".join(lines) + "\n"
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content)
    return str(out)


def main():
    parser = argparse.ArgumentParser(description="Generate LAMMPS inputs using ASE")
    parser.add_argument("--input", required=True, help="Input structure (POSCAR/CIF)")
    parser.add_argument("--job-type", required=True,
                        choices=["minimize", "nvt", "npt", "nve"],
                        help="Simulation type")
    parser.add_argument("--pair-style", default="eam/alloy",
                        help=f"LAMMPS pair style. Options: {list(PAIR_STYLES.keys())}")
    parser.add_argument("--pair-coeff", required=True,
                        help="pair_coeff line (e.g., '* * Si.eam Si')")
    parser.add_argument("--output-dir", default="lammps_input", help="Output directory")
    parser.add_argument("--params", type=str, default="{}",
                        help="JSON string of additional parameters")
    args = parser.parse_args()

    try:
        params = json.loads(args.params)
        output_dir = Path(args.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        # Convert structure
        data_path = str(output_dir / "data.lammps")
        struct_info = structure_to_lammps(args.input, data_path)

        # Generate input script
        input_path = str(output_dir / "in.lammps")
        generate_input_script(
            args.job_type, "data.lammps", args.pair_style, args.pair_coeff,
            input_path, params,
        )

        result = {
            "status": "success",
            "job_type": args.job_type,
            "pair_style": args.pair_style,
            "files_generated": [input_path, data_path],
            "structure": struct_info,
        }
        print(json.dumps(result, indent=2))
    except Exception as e:
        print(json.dumps({"status": "error", "message": str(e)}))
        sys.exit(1)


if __name__ == "__main__":
    main()
